---
title: "LASSO"
output: html_document
date: "2023-03-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, results='hide', fig.width=8, fig.height=4, cache=TRUE)
options(scipen=0, digits=3)
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(glmnet, leaps, car, tidyverse, mapproj, gridExtra, ggrepel, plotly, skimr, usmap)
```

```{r}
data.fl <- read.csv('data/CrimeData_FL.csv',header=T,na.string=c("","?"))
names(data.fl)
skimr::skim(data.fl)
```
```{r}
is.na(data.fl)[1:3,1:3]
```
```{r}
fit.fl.lm <- lm(violentcrimes.perpop~., data.fl)
summary(fit.fl.lm)
#Anova(fit.fl.lm)
```
```{r}
dim(data.fl)
```
```{r}
Y <- data.fl[,98]
X.fl <- model.matrix(violentcrimes.perpop~., data=data.fl)[,-1] #-1 here removes a col named "intercept" from the matrix
colnames(X.fl)
```
```{r}
fit.fl.lambda <- glmnet(X.fl, Y, alpha=1, lambda=50)
names(fit.fl.lambda)
```
```{r}
fit.fl.lambda$lambda
```
```{r}
fit.fl.lambda$beta
```
```{r}
tmp_betas <- fit.fl.lambda$beta
fit.fl.lambda$df
```
```{r}
fit.fl.lambda$a0
```
```{r}
coef(fit.fl.lambda)
```
```{r}
coef.100 <- coef(fit.fl.lambda, s=100)
coef.100 <- coef.100[which(coef.100 !=0),]
coef.100
```
```{r}
rownames(as.matrix(coef.100))
```
```{r}
fit.fl.lambda <- glmnet(X.fl,Y, alpha=1)
plot(fit.fl.lambda)
```
```{r}
#fit.fl.lambda$lambda
str(fit.fl.lambda)
```
```{r}
names(data.fl)
Y <- data.fl[,98]
X.fl <- model.matrix(violentcrimes.perpop~.,data=data.fl)[,-1]
set.seed(10)
fit.fl.cv <- cv.glmnet(X.fl,Y,alpha=1,nfolds=10)
plot(fit.fl.cv)
X.fl
```
```{r}
names(fit.fl.cv)
```
```{r}
#fit.fl.cv$cvm
#plot(fit.fl.cv$lambda)
plot(fit.fl.cv$lambda, fit.fl.cv$cvm, xlab="lambda", ylab="mean cv errors")

```
```{r}
plot(fit.fl.cv$lambda, fit.fl.cv$nzero)
```
```{r}
coef.min <- coef(fit.fl.cv, s="lambda.min")
coef.min <- coef.min[which(coef.min!=0),]
as.data.frame(coef.min)
```
```{r}
coef.min <- coef(fit.fl.cv, s="lambda.min")
var.min <- coef.min@Dimnames[[1]][coef.min@i + 1][-1]

Y <- data.fl[,98]
X.fl <- model.matrix(violentcrimes.perpop~., data=data.fl)[,-1]
set.seed(10)
#t <- as.matrix(data.fl[,-ncol(data.fl)])
fit.fl.cv <- cv.glmnet(X.fl, Y, alpha=1, nfolds=10, intercept=T)
plot(fit.fl.cv)
```
```{r}
coef.min <- coef(fit.fl.cv, s="lambda.min")
coef.min <- coef.min[which(coef.min!=0),]
rownames(as.matrix(coef.min))[-1]
```
```{r}
fit.fl.force.cv <- cv.glmnet(X.fl, Y, alpha=1, nfolds=10, intercept = T, penalty.factor =c(0,rep(1,ncol(X.fl)-1)))
coef.force.min <- coef(fit.fl.force.cv, s="lambda.min")
var.force.min <- coef.force.min@Dimnames[[1]][coef.force.min@i+1][-1]
var.force.min
```
```{r}
var.min2 <- coef(fit.fl.cv, s="lambda.min")
var.min2 <- var.min2[which(var.min2!=0),]
list <- rownames(as.matrix(var.min2))[-1]
data.fl.sub <- data.fl[,c("violentcrimes.perpop",list)]
fit.min.lm <- lm(violentcrimes.perpop~., data=data.fl.sub)
summary(fit.min.lm)
```
```{r}
comp <- data.frame(coef.min, summary(fit.min.lm)$coef[,2])
names(comp) <- c("LASSO Estimates", "Lm Estimates")
comp
```
```{r}
data.fl.sub <- data.fl[c("violentcrimes.perpop",list)]
#names(data.fl.sub)
fit.final.1 <- regsubsets(violentcrimes.perpop~., nvmax=15, method="exhau", data.fl.sub)
plot(summary(fit.final.1)$cp)
```
```{r}
fit.final.1.s <- summary(fit.final.1)
opt.size <- which.min(fit.final.1.s$cp)
final.var.1 <- fit.final.1.s$which
final.var <- colnames(final.var.1)[final.var.1[opt.size, ]][-1]
final.fit <- lm(violentcrimes.perpop ~., data.fl[, c("violentcrimes.perpop", final.var)])
summary(final.fit)
par(mfrow=c(1,2))
plot(final.fit, 1)
plot(final.fit, 2)
```